# Generated by Django 4.2.1 on 2023-05-23 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='2023-05-23 18:44:02')),
                ('cliente_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='administrador.cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codigo_de_barras', models.IntegerField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('precio_compra', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('nombre', models.CharField(max_length=60)),
                ('unidades_vendidas', models.IntegerField()),
                ('ganancia', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('nit', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=20)),
                ('productos', models.TextField()),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['nit'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valor_producto_comprado', models.IntegerField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='administrador.factura')),
                ('productos_codigo_de_barras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='administrador.productos')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id_factura'],
            },
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedor_nit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='administrador.proveedor'),
        ),
    ]
