# Generated by Django 4.2.1 on 2023-05-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(verbose_name='2023-05-23 18:47:31'),
        ),
    ]
