# Generated by Django 4.2.1 on 2023-05-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0004_alter_factura_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente_cedula',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='id_factura',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productos_codigo_de_barras',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
