# Generated by Django 4.1.9 on 2023-05-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0005_remove_factura_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='proveedor_nit',
            field=models.IntegerField(),
        ),
    ]
