# Generated by Django 4.2.1 on 2023-05-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0005_remove_factura_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=60, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(verbose_name='2023-05-24 10:00:04')),
                ('cliente_cedula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='cajero.cliente')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('valor_producto_comprado', models.IntegerField()),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='cajero.factura')),
                ('productos_codigo_de_barras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d', to='administrador.productos')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id_factura'],
            },
        ),
    ]
