# Generated by Django 4.2.1 on 2023-05-24 23:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
