# Generated by Django 4.2.1 on 2023-05-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0004_alter_factura_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(verbose_name='2023-05-27 20:21:15'),
        ),
    ]
