# Generated by Django 4.1.9 on 2023-05-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0006_alter_factura_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente_cedula',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_factura',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='productos_codigo_de_barras',
            field=models.IntegerField(max_length=20),
        ),
    ]
