# Generated by Django 4.1.9 on 2023-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0007_alter_factura_cliente_cedula_alter_factura_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='id_factura',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='productos_codigo_de_barras',
            field=models.IntegerField(),
        ),
    ]
