# Generated by Django 4.1.9 on 2023-05-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cajero', '0008_alter_venta_id_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente_cedula',
            field=models.IntegerField(),
        ),
    ]
